#!/usr/bin/bash

# Requires installing mecab

# Open GoldenDict, press "Edit" > "Dictionaries" > "Programs" and add this script as type html.
sanitize_input() {
    sed -E 's,[a-z]+, ,Ig'
}

select_word(){
  sed "s|$1\">\($1\)|$1\"><b>\1</b>|"
}

mecab_implementation(){
  printf "<h1>$(mecab \
		  --node-format='<a href="bword:%m">%m</a> ' \
      		  --eos-format='<br> ' \
      		  --unk-format='%m' \
		  -u ~/.local/share/Anki2/addons21/1225470483/mecab_controller/support/user_dic.dic) </h1>"
}

clipboard=$(xclip -o | sanitize_input)
[[ "$clipboard" != *"$1"* ]] && xclip -i <<< "$1" && clipboard=$1
mecab_implementation <<< "$clipboard" | select_word "$1"
