#!/bin/bash

set -euo pipefail

# Requires installing mecab

# Open GoldenDict, press "Edit" > "Dictionaries" > "Programs" and add this script as type html.

FONT_SIZE=2rem
GDWORD=""
# Default path to user_dic.dic, assuming that the user ran `make install`.
USER_DICT=/usr/share/gd-tools/user_dic.dic

sanitize_input() {
	sed -E 's,[a-z]+, ,Ig'
}

usage() {
	local -r bn=$(basename -- "$0")
	cat <<-EOF
		usage: $bn [OPTIONS] WORD

		echo input back to GoldenDict as HTML with sentence split into parts

		OPTIONS
	EOF
	column -t -s'|' <<-EOF
		  --user-dict PATH|path to the user dictionary.
		  --font-size SIZE|font size. The default value is 30px
	EOF
}

mecab_split() {
	if ! command -v mecab &>/dev/null; then
		echo "Error: MeCab is not installed. Please install MeCab and try again."
		exit 1
	fi

	mecab \
		--node-format='<a href="bword:%f[6]">%m</a> ' \
		--unk-format='<a href="bword:%m">%m</a> ' \
		--eos-format='<br> ' \
		--userdic="${USER_DICT}"

}

print_css() {
	cat <<-EOF
		<style>
			.gd-mecab {
				font-size: ${FONT_SIZE:-2rem};
				margin-bottom: 0.05em;
				margin-top: -0.2em;
				color: #1268c3;
				font-weight: normal;
			}

			.gd-mecab a {
				display: inline-block;
				font-weight: normal;
				color: royalblue;
				text-decoration: none;
				border-bottom: dashed 2px currentColor;
			}

			.gd-mecab a b {
				background-color: #ddeeff;
				border-radius: 0.2rem;
				font-weight: 500;
			}
		</style>
	EOF
}

highlight_word() {
	local target_word=$* search=""
	search=$(cat -- -)
	search=${search//">$target_word<"/"><b>${target_word}</b><"}
	echo "$search"
}

get_clip_sentence() {
	clip_sentence=$(xclip -o -sel primary | sanitize_input)
	if [[ "$clip_sentence" != *"$GDWORD"* ]]; then
		xclip -i -sel primary <<<"$GDWORD"
		clip_sentence=$GDWORD
	fi
	echo "$clip_sentence"
}

main() {
	if (($# == 0)) || [[ $* == --help ]] || [[ $* == -h ]]; then
		usage
		exit
	fi
	while (($# > 0)); do
		case $1 in
		--font-size)
			shift
			FONT_SIZE=$1
			;;
		--user-dict)
			shift
			USER_DICT=$1
			;;
		*)
			GDWORD="${GDWORD}$1"
			;;
		esac
		shift
	done

	echo '<div class="gd-mecab">'
	get_clip_sentence | mecab_split | highlight_word "$GDWORD"
	echo '</div>'
	print_css
}

main "$@"
