#!/usr/bin/bash

# Requires installing mecab

# Open GoldenDict, press "Edit" > "Dictionaries" > "Programs" and add this script as type html.
sanitize_input() {
    sed -E 's,[a-z]+, ,Ig'
}

select_word(){
  sed "s|\(<a href=\"bword:$1\">$1</a>\)|<span style=\"background-color: lightblue\">\1</span>|"
  # [[ $clipboard != $1 ]] && sed "s|\($1\)|<span>\1</span>|" || echo "$1"
}

mecab_implementation(){
  # Comment out exactly one of the implementations
  # 1
  printf "<h1>
  $(echo "$1" | mecab \
		--node-format='<a href="bword:%m">%m</a> ' \
		--eos-format='<br> ' \
		--unk-format=' ')
  </h1>"
  # 2 has to be installed first
  # furigana_link_split
}

clipboard=$(xclip -o | sanitize_input)
[[ "$clipboard" != *"$1"* ]] && xclip -i <<< "$1" && clipboard=$1
mecab_implementation $clipboard | select_word "$1"
# select_word "$1" <<< "$clipboard" | mecab_implementation
