on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "**"

name: "Run Shellcheck"

permissions: read-all

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: "Run ShellCheck"
        uses: ludeeus/action-shellcheck@00b27aa7cb85167568cb48a3838b75f4265f2bca # master
        with:
          additional_files: 'gd-*.sh'
